### ISSUE TITLE
considering result about Anderj

### ISSUE THREAD

**Issue by writerityyuko** [timeriver/HumanResources#105]
collect and fill out comments in the spreadsheet
inform to Hide

**Comment by writerityyuko** [comment]
@writerity-t-bojan 

If you finished to fill out information into the spreadsheet, ask  Hide to consider about him. thanks.

**Comment by writerity-t-bojan** [comment]
@writerityyuko I have finished, I will inform him now.

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
if Dimitar say he is okay, then tell SAC
if they dont reply for more than a week, then plz tell me
i can ask them

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe I informed SAC about Andrej's results.

**Comment by writerity-t-bojan** [comment]
@writerityyuko Andrej accepted the offer.
