### ISSUE TITLE
Update "Writerity Recruit" spreadsheet

### ISSUE THREAD

**Issue by writerityyuko** [timeriver/HumanResources#124]

**Comment by writerityyuko** [comment]
@writerity-t-bojan 

Could you check the list and fill out if there is things which is not updated (ex., result of exam)?
thanks in advance.

**Comment by writerity-t-bojan** [comment]
@writerityyuko I updated the recruiter list.

**Comment by writerityyuko** [comment]
@writerity-t-bojan 

thanks for your work.
but could you check the cell K91~K93 of Developer tab sheet again?

**Comment by writerityyuko** [comment]
@writerity-t-bojan 
ok, thank you.
