### ISSUE TITLE
Renew the job advertisement only for Designers on social media

### ISSUE THREAD

**Issue by writerity-t-bojan** [timeriver/HumanResources#140]

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe @writerityyuko Can you please tell me it's ok to proceed with this task. I want to renew only the job advertisement about the Designer job position. 
Is it ok not to renew the job advertisement for Developers and Interns because in the upcoming period the Designers are higher priority and it's better to focus on them. 
Anyhow if there are new applicants for the Developer job position we will take them into considiration as well. Thank you.

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
for Developers, can you just renew the ads for only senior?

**Comment by writerityyuko** [comment]
@writerity-t-bojan 

no problem for me.

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe Can you please tell me only for Senior Web, or for Senior Web and Senior App as well? Thank you.

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
changed my mind. no ads for developers. you can focus on designers
