### ISSUE TITLE
Set 2nd exam for Dejan

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/HumanResources#146]
Toki will check skill by 2nd exam

plz ask him when he is available (3 options)
ex)
1. 1/29Tue : 5pm~
2. 1/30Wednesday : 7pm~
3. 1/31Thurday : 5pm~

etc

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe I'm trying to get in touch with Dejan, as soon as I talk with him, I will inform you about the second exam.

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe I talked with Dejan he will come on Wednesday, 1/30 at 7pm for the second exam.

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
no i meant
we need 3 options when he is available
so that i can ask Toki when he can make some time for the exam

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe Dejan is available every day this week after 5pm.

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
thanks

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
is he available some day in the morning or early afternoon?

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe I tried to contact him for several times, he is not answering his phone at the moment.

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe Dejan informed me that the best time for him will be during the weekend. But he also mentioned that if it is necessary he can come to the office after 5pm throughout the week. He can't be earlier due to work commitments.

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
no need to come because anyway Toki is not here and anyone else like Jovica cannot help.

so if weekends, can be more earlier?
what time is the best for him?

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe He can do it during the weekend and early in the day. He is flexibile and said we to determine the hour for the exam.

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
okay plz let him wait for a while

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe Can you please tell when is the exam because Saturday is Feb 2,  or should be on Feb 3, Sunday?

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
oh sorry
2/3 Sunday 9am

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe I messaged Dejan about the exam, still I'm waiting for an answer.

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe I talked with Dejan and I set up the exam for February 3, Sunday, 9am, he will work from home. 
His skype id is: Bozinoski996

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
thank you.
