### ISSUE TITLE
Give offer to 2 new candidate after pc delivery date is fixed

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/HumanResources#151]
first we need to check pc delivery date
then we can know when they can start to work

---
Andrej Lazarevski
and
Aleksandar Mihailovski

300EUR / 6 months / engagement contract

1month - engagement contract
after that, depends on their skill

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe Tomorrow me and Elena will go to pick up the two pc's. As up until now I'm still waiting a reply from Aleksandar about the offer.

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe @writerityyuko Aleksandar informed me that he accepts the offer. Today we are going to pick up the new pc for the two of them. Can you please tell me when will be their starting date as an employees? Thank you.

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
okay i will let you know later

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan @writerityelena 
plz tell Andrej
the contract will be employment contract from 1st month (confirmed with Kaichi-san)

plz tell Aleksander
what about 300EUR / 6months / employment contract

**Comment by writerityelena** [comment]
@writerity-watanabe 
we will have answer until Monday

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay thanks

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe @writerityyuko Andrej and Aleksandar are starting on Tuesday, 12th February, 08:30.
