### ISSUE TITLE
Employment contract with Oliver

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/HumanResources#159]
plz

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe Can you please tell me about contract conditions: salary, period, starting date etc. Thank you.

**Comment by writerity-watanabe** [comment]
same 
5month (total 6 months including first month for engagement)
after 1 months

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe @writerityyuko I prepared the employment contract for Oliver. His first month will end on the 2/15/2019. Can you please tell if it is ok, thank you.

https://docs.google.com/document/d/1ywfHGfOCz5Jl7mSXS9K1efgVsXSjvXu26AINZK8m2Os/edit#

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
okay checked

**Comment by writerityyuko** [comment]
@writerity-t-bojan 

I cheked it as well. thanks for your work.

**Comment by writerityyuko** [comment]
FMI

Feb15 for making contract
