### ISSUE TITLE
Arrangement Interview of English teacher, Dijana

### ISSUE THREAD

**Issue by writerityyuko** [timeriver/HumanResources#16]

**Comment by writerityyuko** [comment]
@writerityelena 
If there is progress, let me know. thanks.

**Comment by writerityelena** [comment]
@writerityyuko 
I sent e-mails and put you in CC , no reply yet

**Comment by writerityyuko** [comment]
@writerityelena 

ok. thanks

**Comment by writerityelena** [comment]
@writerityyuko np

**Comment by writerityelena** [comment]
@writerityyuko 
Sinolicka approved interview data Dec 18 at 13:00 PM

**Comment by writerityyuko** [comment]
@writerityelena 

ok. Thanks. 
by the way,  this task card is for Dijana.

**Comment by writerityelena** [comment]
@writerityyuko 

すみません  and thank you

**Comment by writerityyuko** [comment]
It has been canceled due to her reason. (offered interview but no response)
