### ISSUE TITLE
Aleksandar employment contract 12th

### ISSUE THREAD

**Issue by writerityyuko** [timeriver/HumanResources#165]

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe @writerityyuko The contract is ready for signing.

https://docs.google.com/document/d/1hSQTen9nLH-gVhEIaY48SXKF3VdHv_eBDAhXzXPPeQY/edit

**Comment by writerityyuko** [comment]
@writerity-t-bojan 

Thank you for your work. and 
Can I have Aleksandar's birthday data?
due to need it for my management task assigned by SAC.

**Comment by writerity-t-bojan** [comment]
@writerityyuko Aleksandar birth date is 03.02.1996.

**Comment by writerityyuko** [comment]
@writerity-t-bojan 

Thanks!
just in case,  is it Feb 3rd, right?

**Comment by writerity-t-bojan** [comment]
@writerityyuko Yes.
