### ISSUE TITLE
Andrej employment contract 12th

### ISSUE THREAD

**Issue by writerityyuko** [timeriver/HumanResources#166]

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe @writerityyuko The contract is ready for signing.

**Comment by writerityyuko** [comment]
@writerity-t-bojan 

ok. thank you.

**Comment by writerityyuko** [comment]
@writerity-t-bojan 

Can I have Andrej's birthday data?
due to need it for my management task assigned by SAC. thanks.

**Comment by writerity-t-bojan** [comment]
@writerityyuko Andrej's birth date is 02.01.1997.
