### ISSUE TITLE
Stop hiring designers in Feb

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/HumanResources#177]
even if there is a good candidate, we cannot hire him/her

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe No problem, but I will need feedback from the clients for the ones that sent us the exam back, so I can notify them via e-mail. Thank you.

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
okay

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe can you please talk with the clients about no.40 Aleksandra Cakikj, there is no feedback. Thank you.

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe can you please tell if there is an update about this candidate? Thank you.
https://docs.google.com/spreadsheets/d/1YkPIO9s6wpP-Fugl0n-KbNjCqF9A-vt_grrH3FRveuU/edit#gid=370160821
> @writerity-watanabe can you please talk with the clients about no.40 Aleksandra Cakikj, there is no feedback. Thank you.

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
not yet sorry.
will ask them again

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe any update about applicant no.40 Aleksandra Cakikj, I will have to inform her about the results from her exam. She had her exam on 2/1, thank you.

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
will ask again

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
They just replied and said we do not hire him

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe thanks.
