### ISSUE TITLE
Inform applicants about Company decision for hiring

### ISSUE THREAD

**Issue by writerity-t-bojan** [timeriver/HumanResources#184]

**Comment by writerity-t-bojan** [comment]
@writerityyuko I informed the applicants for the Motion Graphic Designer job opening about our decision to hire them.
1. No.37 Oliver Kostoski
2. No.38 Ago Musa (he didn't send the exam back)
3. No.39 Gjorgi Malzarkov
4. No.41 Sasho Radulov
About no.40 Aleksandra Cakikj I am waiting the feedback from SAC afterwards I will inform her.

**Comment by writerityyuko** [comment]
@writerity-t-bojan 

ok, thank you for your work.
