### ISSUE TITLE
Post job advertisement on  recruitment website as IT.mk

### ISSUE THREAD

**Issue by writerity-t-bojan** [timeriver/HumanResources#209]

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe @writerityyuko I contacted with IT.mk again about the opportunity to post job ads at their site and this is their reply, regarding my question about the specifics for job posting:
In relation to the content of the advertisement, there are no restrictions, you give us the advertisement and the e-mail address at which the interested candidates apply.
We publish the advertisement, we place it on a fixed position on the homepage of IT.mk in the IT Career section for greater visibility. And, at the IT Career section stands at the first position, that means, when you open the IT Career section, your ad will appear first.
Then the same ad is posted on social networks.
Position of the ad:
Homepage + IT Career + it is shared 1x on Facebook + LinkedIn + Twitter with a note [sponsored].
Price 3000MKD without VAT
Duration: 1 week
For payment, we send you an invoice after which you make the payment.
Please advise if it is ok to proceed with them. Thank you.

**Comment by writerityyuko** [comment]
@writerity-t-bojan 

this, IT.mk, is more expensive than the last job advertisement web?

**Comment by writerity-t-bojan** [comment]
@writerityyuko according to the recruit sheet, najdi rabota is cheaper:
1. 1 week advertising with our company logo = 1900 denars without VAT.
2. 1 week advertising without our company logo = 690 denars without VAT.

**Comment by writerityyuko** [comment]
@writerity-watanabe  @writerity-t-bojan 

ok.
well.., so what we gonna do?
I would like to try new one, IT.mk but ...,

Hide? What do you think? 
新しい求人広告サイト試したいんですが、前のよりちょっと高めのようで。。新しいの試したいんですけど、迷います。。

**Comment by writerity-watanabe** [comment]
@writerityyuko 
はい、試したいですが、
一旦seniorレベルの条件を精査します！

**Comment by writerityyuko** [comment]
@writerity-watanabe  @writerity-t-bojan 

そしたら、一度条件が確定するまで、待ちますね。

Bojan, 
Hide is considering the requirement for the senior developer role.
so wait for fixing it and decide later. Hide says that he would like to try  IT.mk as well thoguh.

**Comment by writerity-t-bojan** [comment]
@writerityyuko No problem, I will wait, after the decision is made I will upgrade the draft version of the developer's job ad and it will be ready for posting.

**Comment by writerity-watanabe** [comment]
@writerityyuko
下記、条件です！
- ios, android, laravel, vuejsの経験（言語使用経験年数は問わないが、長いほうがベター）
- プロジェクトマネジメント経験
- 実務経験5年以上
- 将来的に日本で働ける人

→NET：1200EUR〜で雇用可能です。＊採用までは今まで通りのフロー、時川さんが試験結果を確認or試験を監督

広告、更新するかどうかはその時に判断しますので、勝手に更新されないようにお願いします。

**Comment by writerityyuko** [comment]
@writerity-watanabe 

すみません。こちらご連絡いただいていたのにすっかり確認が遅れてしまっていました。
シニアの条件、ありがとうございます。
こちらをボヤンに伝えます。

今後のシニア募集に関する活動ですが・・・、

> 広告、更新するかどうかはその時に判断しますので、勝手に更新されないようにお願いします。

シニアデベロッパーの募集広告を更新をするかしないかはまだ決めていない、ということですか？

**Comment by writerity-watanabe** [comment]
@writerityyuko 
いえ、
シニアデベロッパーの募集広告はit.mkで出してみて良いのですが
掲載期間が決まっていたと思うので、毎回更新時に更新するかはその時の判断で・・とさせてください！
＊採用してもとりあえずは1名なので・・

**Comment by writerityyuko** [comment]
@writerity-watanabe 

あ！そういうことか。失礼しましたー。
まずは1回出してみて、更新時期になったら、その都度ご相談しますー。

**Comment by writerityyuko** [comment]
@writerity-t-bojan 

Must have;

- professional developent experience of iOs, Android, Laravel, Vuejs ( preferred longer experience)
-experience of prroject management
-work experience more than 5 years
-available to work in Japan in the future

NOTE to Bojan,
- we can pay compensation more than 1,200 euro for this position.
- recruitment activities is same as we are doing now. but perhaps Toki will watch/organize an exam and its result directly.

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe @writerityyuko This is a draft version for Senior Developer Position.

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe @writerityyuko This is a draft version for the Senior Developer Position.
- Experience in iOS, Android, Laravel, Vuejs (preferred longer experience) development for over 5 years,
- Experience of project management,
- Wiling to learn and adapt to a fast-paced environment,
- Good communication skills,
- Ability to understand client's needs,
- A possibility to be relocated in Japan in the future.
I have some points regarding project management.
Can you please explain exactly what will be his/her PM commitments, because it is very difficult, almost impossible to have Dev and PM experience in 5 years. The time is too short and these are very big areas of expertise. In practise people transfer from Development to PM if they want to have more coordinating role, but we are talking about people with 10-15 years experience.
We can try instead of experience of PM:
- Team leading and mentoring experience and preference or,
- With preference in future to be involved in PM.
This is of course merely my suggestions and poin of view, but please advise how to proceed with the ad. Thanks.

**Comment by writerityyuko** [comment]
@writerity-t-bojan 

as we talked now, thank you. It is fine for me.

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
okay try 
> Team leading and mentoring experience and preference or,
With preference in future to be involved in PM.
This is of course merely my suggestions and poin of view, but please advise how to proceed with the ad. Thanks.
