### ISSUE TITLE
Update recruitment sheet with new applicants

### ISSUE THREAD

**Issue by writerity-t-bojan** [timeriver/HumanResources#219]

**Comment by writerity-t-bojan** [comment]
@writerityyuko Today we have 9 applicants:
1. no.24 Office Administrator (1)
2. no. 112 and no.116 Junior Web Developer (2)
3. no.113, 114, 115, 117, 118, 119 Intern Developer (6)

**Comment by writerityyuko** [comment]
@writerity-t-bojan 

ok, thanks. we"ll check them.
