### ISSUE TITLE
Renewal of contract for Dragana

### ISSUE THREAD

**Issue by writerity-t-bojan** [timeriver/HumanResources#253]

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe @writerityyuko Dragana current contract expires on 3/24/19. Can you please tell me details about the renewal: starting date, duration, salary, etc so I can prepare the contract on time. Thank you.

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
okay i will tell you when its fixed

now Dragana and I are talking about it
and i hope she will give me her expectation and reason (and her work plan for next term)

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe any updates, Dragana contract expires on the 24th March

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
today i talk with her and she will decide

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
she will tell me her decision tomorrow and let you know

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan
decided 
350EUR 6months

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe please take a look if it is ok to print

https://docs.google.com/document/d/1P28JB1cnmIGwOud-r6Gsgzs--OitHbXOB6KF7P4thWM/edit

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
okay go ahead
