### ISSUE TITLE
Update website with data privacy statement

### ISSUE THREAD

**Issue by writerity-t-bojan** [timeriver/HumanResources#263]

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe @writerityyuko as we spoke, it will be better to add data privacy consent statement on our website in order to protect ourselves how we keep personal data from applicants.
When applicant fills the form and upload his cv, before he/she clicks send button, to appear like a pop up window a privacy statement that he agrees to share the information with us. Agreeing will be condition for him/her to continue with the process of applying. The send button will be example grey and he can't send us his cv until he agrees with the privacy statement. Is it ok to proceed with the developers on this matter?

https://docs.google.com/document/d/1RKxcuZkMX4pqFs7tA_mu14Kqz-wbC1HMJcX8nM7Wh6U/edit

**Comment by writerityyuko** [comment]
@writerity-t-bojan 

I like your idea. 

@writerity-watanabe 

How about you?

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
ok

**Comment by writerity-t-bojan** [comment]
@writerityyuko @writerity-watanabe It is done.

**Comment by writerityyuko** [comment]
@writerity-t-bojan 

thanks.  it is good.
