### ISSUE TITLE
Report on job ad about Senior Developer

### ISSUE THREAD

**Issue by writerity-t-bojan** [timeriver/HumanResources#268]

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe @writerityyuko I made a short report about the job ad. Can we please have a meeting regarding this topic when you will be available. I will post a screenshot with translation as well.

https://docs.google.com/document/d/1UqE4YNz0YmEfatnOkowzvtWjsRmmTx1g7C68Heh21T0/edit

![Screenshot](https://user-images.githubusercontent.com/45934340/54524827-302f8c80-4973-11e9-979a-a395c6bc019d.png)

The comments were made by the head of development in another IT company in Skopje saying that the ad in general is too ambitious regarding the skills we are looking for one person.

Thank you for your time.

**Comment by writerityyuko** [comment]
@writerity-t-bojan 

oh, ok. better to talk with Hide soon.

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe please tell me when you we will be available to have a meeting, thanks.

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
check comment
https://docs.google.com/document/d/1UqE4YNz0YmEfatnOkowzvtWjsRmmTx1g7C68Heh21T0/edit
