### ISSUE TITLE
Create annex for engagement contract

### ISSUE THREAD

**Issue by writerity-t-bojan** [timeriver/HumanResources#270]

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe can you take a look at the annex for my engagement contract before signing? Thanks.

https://docs.google.com/document/d/1uA5UFYFxvL2WJuwgNGPyB2SKiFeoRKmZeDZrb0Pp8XU/edit

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
okay done
