### ISSUE TITLE
Give offer to Angelina

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/HumanResources#271]
1 month
100EUR

Public Relations
System Development

offer in email to keep all proof

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe I will inform her via e mail today.

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe Angelina accepted the offer and via email. When will be her starting date, do we need something to buy for her like equipment?

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
okay then next monday if she can
about equipment, if we dont have one, plz buy
same keyboard, same mouse, mousepad...etc

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
she will sit next to Dimitar
plz take all equipment from the desk and prepare

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe all prepared, Jovica told me 90% of the lap top is ready, minor updates for Monday morning.
