### ISSUE TITLE
Prepare contract for intern

### ISSUE THREAD

**Issue by writerity-t-bojan** [timeriver/HumanResources#277]

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe @writerityyuko  the contract is ready, can you please take a look, thanks.

https://docs.google.com/document/d/18Jbx-rNy4xEHDn2sgZ2___epBBQyHC0927-17d-FuZE/edit#

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
okay checked
