### ISSUE TITLE
Find and post job advertisement to facebook group  related English teaching

### ISSUE THREAD

**Issue by writerityyuko** [timeriver/HumanResources#34]

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe @writerityyuko I modified the job advertisement relating English Teacher which has to be post. 
The job advertisement description has to be modified on the Writerity site as well, before I post it to the facebook groups.

[Job Description-1.docx](https://github.com/timeriver/recruitment/files/2689603/Job.Description-1.docx)

**Comment by writerityyuko** [comment]
@writerity-t-bojan 
I will check it. wait for a while.

**Comment by writerity-t-bojan** [comment]
@writerityyuko  
Modified job advertisment
[Job.Description-1.docx](https://github.com/timeriver/recruitment/files/2690223/Job.Description-1.docx)

**Comment by writerityyuko** [comment]
▼Job Description
before:
English teacher position in our company is for the job training center which we will open in this winter. The center will provide several courses for learning languages and IT skills for job skill learners in Japan. We will provide classes by online and in-class at Skopje.

After:
The English Teacher position in our company is open for the job training center which will start operating this winter, where several courses for learning languages and IT skills will be available for everyone looking to advance their job skills in Japan. The center will provide both online and in-class sessions in Skopje.

**Comment by writerityyuko** [comment]
@writerity-watanabe 

本件、英語教師の募集に関するウェブサイトの修正依頼を”Writerity.com進行管理ボード”のほうにポストしました。
ただ、何か準備が必要とおっしゃっていたので、DraganaをAsighneeにはまだ設定していない状態なのですが、変えたほうがよいでしょうか？

**Comment by writerity-watanabe** [comment]
@writerityyuko 
アサインはしておいて良いです！
準備は終えたのですが、まだSAC優先タスクがありますので、それが終わり次第
Dragana→渡邊へ報告もらう予定です。
それから僕が坂口さんへGO出して、細かな説明があれば直接していただくフローにしたいです！

**Comment by writerityyuko** [comment]
@writerity-watanabe 
承知しました。

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe @writerityyuko 
Can I post a written English Teacher job advertisement with modified text and writerity's career e-mail on the facebook groups? That way we can save time, till the developers update the company's website with the modified job advertisement.

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe @writerityyuko I have posted the English Teacher job advertisement to two facebook groups.
