### ISSUE TITLE
Make new Annex for Jovica

### ISSUE THREAD

**Issue by writerityelena** [timeriver/HumanResources#38]

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe @writerityyuko @writerityelena I made the annex for Jovica so if it's ok to proceed.

https://docs.google.com/document/d/1FGPzFPKlaUuuNXVxOcDQZyKvGcVXMC5Ry4CwP0a0cEc/edit

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
plz give me permission

btw plz write expired date there even if its annex
1 year from Jan 16

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe I will make the change

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
just checked
no more problem

**Comment by writerityelena** [comment]
@writerity-watanabe 
Annex is good, i can print ?

**Comment by writerity-watanabe** [comment]
@writerityelena 
just noticed

```
ANNEX NO.2
To the employment contract  concluded between the contracting parties on  25.01.2018
```

why Jan 25, 2018?

**Comment by writerityelena** [comment]
@writerity-watanabe 
the contract that we have and was done by the first admin doesn't have date , so we checked the doc from Employment Agency and that is the day when Jovica starts working

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay you can print
