### ISSUE TITLE
Update on the applicants status

### ISSUE THREAD

**Issue by writerity-t-bojan** [timeriver/HumanResources#44]

**Comment by writerityyuko** [comment]
@writerity-t-bojan 

This is your task, maybe?
let me know what is this task?

**Comment by writerity-t-bojan** [comment]
@writerityyuko I opened this task, so that we can update together with Elena the candidate's status list.

**Comment by writerity-t-bojan** [comment]
@writerityyuko We updated the candidate's list for developers, designers, admin staff/teachers.
