### ISSUE TITLE
Inform the result to Sinolicka-EN teacher

### ISSUE THREAD

**Issue by writerityyuko** [timeriver/HumanResources#48]

**Comment by writerityyuko** [comment]
@writerity-t-bojan 

Unfortunately she is not selected and could you inform her that in this week?
Perhaps last half of this week is better.

**Comment by writerity-t-bojan** [comment]
@writerityyuko I will inform Sinolicka from Wednesday onwards.

**Comment by writerity-t-bojan** [comment]
@writerityyuko I informed Sinolicka about our decision.
