### ISSUE TITLE
make sure who is in charge of job interview

### ISSUE THREAD

**Issue by writerityyuko** [timeriver/HumanResources#49]

**Comment by writerityyuko** [comment]
@writerity-watanabe 

面接に同席するメンバーですが、
なんかいつもデベロッパーがあまり協力的でないのが気になっています。
確か前にもお聞きしたと思うのですが、渡邊さんから既に同席するようにアサインされていましたよね？
もしデべ達がそのような認識がないのなら、
オフィシャルに、以下のフォーメーションで今後は面接する、というように認識を合わせておきたいのですが、いかがでしょうか。

▼デベロッパー
渡邊さん（難しい場合は坂口代理）
Jovica（難しい場合はKire代理）
Bojan（難しい場合はElena代理）

▼デザイナー
渡邊さん（難しい場合は坂口代理）
Dimitar
Bojan（難しい場合はElena代理）

▼英語教師、間接部門スタッフ
渡邊さん
坂口
Bojan（難しい場合はElena代理）

**Comment by writerity-watanabe** [comment]
@writerityyuko 
はい、それで問題ないです！
ディベロッパーには別途僕からも伝えます。

**Comment by writerityyuko** [comment]
@writerity-watanabe 

では、上記の通り、スカイプでみんなに流しますね。

**Comment by writerityyuko** [comment]
I would like to make sure who is in charge of job interview again.
Thank you for your co-operation.

▼Developer
Hide ( if impossible, Yuko)
Jovica (if impossible, Kire)
Bojan (if impossible, Elena)

▼Designer
Hide (if impossible, Yuko)
Dimitar
Bojan (if impossible, Elena)

▼English teacher, other positions
Hide 
Yuko
Bojan (if impossible, Elena)
