### ISSUE TITLE
CV or portfolio from candidate | don't make public

### ISSUE THREAD

**Issue by timeriver** [timeriver/HumanResources#5]
dont make it public
always give permission to only specific person.

Desingers
https://drive.google.com/drive/u/0/folders/1Ixy6CTy6TSg0xRLwXlk2O0r7a1ayQsIp?ogsrc=32

Developers
https://drive.google.com/drive/u/0/my-drive?ogsrc=32

Admin &Teachers
https://drive.google.com/drive/u/0/folders/1PykRrsbP2T1DZlvQSVBVswXCURAjin4S?ogsrc=32
[right holders.txt](https://github.com/timeriver/recruitment/files/2685761/right.holders.txt)

**Comment by writerityyuko** [comment]
@writerity-watanabe 
I am thinking to let do this task by Bojan. Is it ok?

**Comment by writerity-watanabe** [comment]
@writerityyuko 
no problem

**Comment by writerityyuko** [comment]
@writerity-t-bojan 

person who have right to see CVs:

Designer：
Hide, Dimitar, Yuko. Elena, Bojan

Developer:
Hide, Jovica, Kire, Yuko. Elena, Bojan

Teacher:
Hide, Yuko. Elena, Bojan

**Comment by writerityyuko** [comment]
@writerityelena 

Could you give permission to me and Bojan to edit this folder?

https://drive.google.com/drive/u/0/folders/1PykRrsbP2T1DZlvQSVBVswXCURAjin4S?ogsrc=32
