### ISSUE TITLE
Inform the result to Vesna-EN teacher

### ISSUE THREAD

**Issue by writerityyuko** [timeriver/HumanResources#74]

**Comment by writerityyuko** [comment]
@writerity-watanabe 

とりあえず、この第一候補の先生から採用どうなっているかの問い合わせも来ているので、
まずは外注での教材開発を打診してみようかと思っているのですが、可能でしょうか？

時給200MKD、発注総額10,000MKDくらい。
委託するのは、インクラスの教材（昨日の打ち合わせの感じだと、インクラスをしっかり作ったほうが、時川さんにはフィットするのかな、という感じだったので。）

![2019-01-23](https://user-images.githubusercontent.com/42671990/51597769-50574800-1efc-11e9-9421-1852c40ea046.png)

**Comment by writerity-watanabe** [comment]
@writerityyuko 
はい、GOで良いか時川と検討します！
また、時川さんの話でもありましたら、
ドイツなど、ヨーロッパの大学事情など、可能であれば調査お願いします！
https://newsphere.jp/national/20171204-4/

**Comment by writerity-watanabe** [comment]
@writerityyuko 
こちら、引き止めないと行けなさそうでしたらGOでokです！

**Comment by writerityyuko** [comment]
@writerity-watanabe 

承知しました。ありがとうございます。

契約は、業務委託契約で、
作業場所は自宅で、内容は教材開発で、お願いしてみようと思いますが、
可能でしょうか？

**Comment by writerity-watanabe** [comment]
@writerityyuko 
はい、大丈夫です！

**Comment by writerityyuko** [comment]
@writerity-watanabe 

ありがとございますー。

**Comment by writerityyuko** [comment]
@writerity-t-bojan 

so, please contact to Vesna to explain the situation.
thanks.

**Comment by writerity-t-bojan** [comment]
@writerityyuko I contacted Vesna and she agrees with the offer and the conditions.

**Comment by writerityyuko** [comment]
@writerity-t-bojan 

thank you for your work.
you help me a lot always.
