### ISSUE TITLE
Update the job advertisements on the company website

### ISSUE THREAD

**Issue by writerity-t-bojan** [timeriver/HumanResources#84]

**Comment by writerity-t-bojan** [comment]
@writerityyuko I updated with track changes the job advertisements that should be modify on the company website, so that we can post them on the facebook group for new developers and designers applicants.

https://docs.google.com/document/d/1p0DNSvKuDyqTcdLSO_j4ptUoL5_0ItinM6m7wVZwg7k/edit

**Comment by writerityyuko** [comment]
@writerity-t-bojan 

Ok. but, Can I see before/after in this file?
I am not sure which parts should be modified.

**Comment by writerity-t-bojan** [comment]
@writerityyuko It's in the edit section, like track changes before/now.

**Comment by writerity-t-bojan** [comment]
@writerityyuko I modified the job advertisements according Dimitar's suggestion

https://docs.google.com/document/d/1p0DNSvKuDyqTcdLSO_j4ptUoL5_0ItinM6m7wVZwg7k/edit#heading=h.lf90g9xpm8g8

**Comment by writerity-t-bojan** [comment]
@writerityyuko I assigned Dragana to update the job advertisements on the company website.

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe Modification on the job advertisements on the company website is finished, can you please tell me if I can proceed with posting them on our Facebook page, Facebook employment group and our Linkedin page.

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
okay. checked

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe @writerityyuko I updated our Facebook, Linkedin page, Jobs and Career in IT (Facebook group), Federal Committee of Developers of the Republic of Macedonia (Facebook group) and Creative Exchange (Facebook group for Designers) with the modified job advertisements for Developers and Designers.
