### ISSUE TITLE
Permission to put designers and developers as assignees

### ISSUE THREAD

**Issue by writerity-t-bojan** [timeriver/HumanResources#87]

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe Can I get a permission so I can put designers and developers as assignee?
In this particular case I need it so that the developers can modify the job advertisements on the company website.

**Comment by writerity-watanabe** [comment]
@writerity-t-bogan
url plz

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe Is this url?

https://github.com/timeriver/gita-report/projects/1

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe Can I please ask you for permission?

https://github.com/timeriver/gita-report/projects/1

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
done
