### ISSUE TITLE
Make contract for the new Video Designer

### ISSUE THREAD

**Issue by writerity-t-bojan** [timeriver/HumanResources#94]

**Comment by writerity-t-bojan** [comment]
@writerity-watanabe @writerityyuko I made a draft engangement contract for the new Video Designer Oliver Stanoevski. Please tell if it's ok to proceed.

[Copy of Engagement contract Oliverdocx.pdf](https://github.com/timeriver/HumanResources/files/2748799/Copy.of.Engagement.contract.Oliverdocx.pdf)

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
can you plz use this format?
https://drive.google.com/drive/folders/12bcicZ7i4mVO0nUQhMKlHR5A-L9RnfH_

> 14.3

14 days’ notice period
→ 90days' notice period
> 14.6

14 days’ notice period
→ 90days' notice period

**Comment by writerityyuko** [comment]
@writerity-watanabe 

we cannot open the file which you sent URL.
渡邊さんが送ってくださったURLのファイルが開けないのですが・・・。

**Comment by writerity-watanabe** [comment]
@writerity-t-bojan 
okay checked.
if Yuko doesnt find any problem, you can use it
