### ISSUE TITLE
11th(Fri)/14:00 Exam Senior Web Developer w/Dejan

### ISSUE THREAD

**Issue by writerity-t-bojan** [timeriver/HumanResources#96]

**Comment by writerityyuko** [comment]
@writerity-t-bojan 

Could you check his result of the exam to Jovica and fill out information into the spreadsheet?
thanks.

**Comment by writerity-t-bojan** [comment]
@writerityyuko Yes, as soon as I get an information from Jovica, will do that.

**Comment by writerity-t-bojan** [comment]
@writerityyuko According to Jovica he had 8/10 at the exam, he is good, but not for the senior position he applied but for lower one. I will set up an interview with him.

**Comment by writerityyuko** [comment]
@writerity-watanabe 

Of course.
I'll leave it to you.
